language: go
matrix:
  include:
    - go: 1.7.5
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip
sudo: true
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
install:
  - glide install
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
